# -*- coding: utf-8 -*-
"""Script Cédulas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPRmww5k4YbioJkBKZORzDdSBRYJd7Og
"""

"""
Este programa tem por objetivo receber um único número inteiro do usuário e
determinar o número total de cédulas que serão expedidas e qual a quantidade
de cada tipo de nota.
"""


def main():
  n = int(input())
  c100 = cedula100(n)
  x = resto100(n)

  c50 = cedula50(x)
  y = resto50(x)

  c10 = cedula10(y)
  z = resto10(y)

  c5 = cedula5(z)
  w = resto5(z)

  c1 = cedula1(w)

  total = c100 + c50 + c10 + c5 + c1

  print('Saque de', total, 'notas:')
  print(c1, 'notas de 1')
  print(c5, 'notas de 5')
  print(c10, 'notas de 10')
  print(c50, 'notas de 50')
  print(c100, 'notas de 100')

def cedula100(n: int) -> int:
  return (n//100)

def resto100(n: int) -> int:
  return (n%100)

def cedula50(y: int) -> int:
  return (y//50)

def resto50(y: int) -> int:
  return (y%50)

def cedula10(z: int) -> int:
  return (z//10)

def resto10(z: int) -> int:
  return (z%10)

def cedula5(w: int) -> int:
  return (w//5)

def resto5(w: int) -> int:
  return (w%5)

def cedula1(d: int) -> int:
  return (d//1)

main()